### ISSUE TITLE
Добавить поиск тэга noscript и получение текста внутри скрипта.

### ISSUE THREAD

**Issue by AlekseyProskurin** [trifonovmixail/seismograph#17]
**Проблема**
1. У нас есть необходимость получение текста внутри тэга noscript. На данный момент это не реализовано.
_Это нужно решить нам, иначе блокируется часть тестов._

_+ еще есть вопрос к Вам:_

**Вопрос**
Подскажите, как можно искать по тексту внутри тэга при использовании PageObject?
_Пример_
Есть кнопка <button class="…….." type="submit">Save</button>. Нужно найти ее по тексту "Save"
`button_save = selenium.PageElement(
    selenium.query(
        selenium.query.BUTTON,
        _class=selenium.query.contains("button-save"),
    )
)
`

**Comment by trifonovmixail** [comment]
selenium.query(selenium.query.DIV, id='some-id' ) это аналог selenium.query('div', id='some-id' ) поэтому константа тут не обязательна, вы модете написать тег просто строкой.

Для поиска кнопки по тексу невозможно обойтись css селекторами (поддерживаются только теги <a> и то не во всех драйверах), а query работает только с css, это не совсем стандарный случай и скорее всего вам нужно использовать find_element_by_xpath, это стандартный метод selenium. Вы можете оформить это как обычное property в PageObject классе  как return self.find_element_by_xpath('...'). Но раз у вас возникла такая ситуация, то скорее всего вы что-то делаете не правильно. Всегда есть возможность прохода по DOM в глубь и получения нужного элемента через обертку. Это более предпочтительный вариант. Учтите что xpath не учитывает вложенность, то есть 
el = self.find_element_by_xpath('...')
el2 = el.find_element_by_xpath('...')

Во втором случаи запрос будет идти не от элемента, а от корня DOM если в xpath явно не указать от куда брать точку отсчета.

**Comment by AlekseyProskurin** [comment]
Я сейчас попробовал получить текст из noscript
`<span class="ui-dropdown-handler-title">
	<span data-marker="user">
		<span style="...">
			<noscript>Georgios Ercan</noscript>
			GE
		</span>
	</span>
</span>`

следующим образом
`from seismograph.ext import selenium


class HeaderUser(selenium.PageItem):
    __area__ = selenium.query(selenium.query.DIV, _class="header-user")


    user_auth = selenium.PageElement(
        selenium.query(
            "noscript"
        ),
        property=lambda we: we.text,
    )`

И мне при вызове user_auth отдало `u''`. Могли бы вы подсказать, что не так?

**Comment by trifonovmixail** [comment]
Попробуйте посмотреть в we.attr.innerHTML

**Comment by AlekseyProskurin** [comment]
Большое спасибо!
