### ISSUE TITLE
Detect TTY on test run and disable color if non-terminal

### ISSUE THREAD

**Issue by zamotivator** [trifonovmixail/seismograph#21]
On my jenkins test run I see following:
``` [32mOK[42m[0m```

I propose to detect on test-run, TTY enabled or not, and on non-TTY stdout disable colored output

```if sys.stdout.isatty():
    # You're running in a real terminal, enable colored output
else:
    # You're being piped or redirected, disable colored output```

**Comment by trifonovmixail** [comment]
Use --no-color flag on command line interface

**Comment by zamotivator** [comment]
Why you have it as an option instead of auto-detect based on "stdout.tty" / "stderr.tty"?

**Comment by trifonovmixail** [comment]
Jenkins has the option "Color ANSI Console Output" and knows how to translate color codes to CSS styles. it feature does not work with auto-detect.

**Comment by zamotivator** [comment]
Thank you, now got it

**Comment by zamotivator** [comment]
Please cl
